### PR TITLE
adds `matchesNode` option

### PR DESCRIPTION
**Pull request by localhostdotdev**
the idea was to show match node on success and fail nodes on errors, for better readability (e.g. 100x less nodes printed :) )

----

sorry there is a lot going on:

- I first did a "prettier" then manual newlines on the project
- then I started working on adding an option to have the behavior I want
- then I rewrote the test grammar (makes it easier to use and more obvious why it's failing)
- then settled on the `matchesNode` option
- (all while writing and rewriting the test file :) )
- then added some documentation in the unlikely event this gets merged

### CODE REVIEW

**Comment by okaxaki** [comment]
Hi, thank you for your pull-request. 

First, applying prettier is very nice. I should have done that before. Thank you very much.

I agree that there is a need for making tree and trace more clean because long trace are difficult to understand - i.e. there is a need removing 'failure' node from  `getParseTreeString()` and 'success' node from `getBacktraceString()` properly.

As for the `getParseTreeString()`, this pull request seems to work correctly because all 'failure' nodes start  and continued from the leaf of the tree.
However, as for the `getBacktraceString()`, some 'success' nodes are occured on the branch of the trace tree. The `matchesNode` implementation will cut a branch at an occurence of a 'success' node.

For example, once we parse the expression `(1 + 1) oh` with `matchesNode` implemented in `test/index.js` of this pull-request, the resulting backtrace are ommited on its way like following:

```javascript
$ node test/index.js '1+1' '(1+1) oh'
...
== getBacktraceString() ==

x 1:9-1:9 /start/additive/plus
| (1 + 1) oh
|         ^
| x 1:9-1:9 /start/additive/multiplicative/mult
| | (1 + 1) oh
| |         ^
| | x 1:9-1:9 /start/additive/multiplicative/divisive/div
| | | (1 + 1) oh
| | |         ^

$ 
``` 
This is the almost same as listing the failure leaf nodes and I felt it is not an expected behavior as the backtrace output.

So, my alternate plan is following. 
- Add `supressFailureNodes` argument for `getParseTreeString`. This removes the failure nodes as the same way of this pull request. The default value is `false` for compatibility.
- Leave the `getBacktraceString()` as it was. 

The above plan also avoids to use the argument `node` which `matchesNode` option takes. The `node` is an still internal data, it is not documented well. So if possible, I would like to stay `node` not being exposed at this moment.

How do you think on this?

Anyway I would like to thank you very much for your kind suggession and pull-request. 
I'm very glad to have a chance to discuss on it.

**Comment by localhostdotdev** [comment]
hi, thanks a lot for taking a look and the thoughtful comment,

i'm working on making a parser with pegjs, it's a bit of a complex one, also the first proper one i ever wrote so i don't understand all the details of everything. it's starting to be quite complex and i'm getting backtraces i have a hard time comprehending.

**prettier**

i ran prettier than manually added newlines after var definitions and before return statements in multi-line functions mainly (to improve readability)

i see a few paths:

- you could run prettier locally but then the newlines would need to be re-added (or not)
  - i used prettier's defaults
  - i would then rebase my changes manually
- you could cherry-pick the first commits (or i could make a separate pull request for formatting)
  - simpler rebase
- this pull request could stay as-is and then tested locally but it makes it hard to see and discuss changes
  - i could rebase my commits into "formatting", "adding option" and "adding tests"

**actual changes**

i'm not very happy about the interface (especially the `state` part), it's more of a quick hack for now.

i think the node part is essential as it allows to do any kind of custom filtering (i have an option to grep the node path for instance and i think i will add more)

i would rather have only one interface to get the graph, e.g. only `getParseTreeString()` and remove `getBacktraceString()`. and then pass options to `getParseTreeString()`, e.g. `getParseTreeString({ types: ['rule.fail'] })` for instance

i'm really not sure about how the graph is actually constructed and what removing nodes does, the output looks correct to me in my limited testing

> However, as for the getBacktraceString(), some 'success' nodes are occured on the branch of the trace tree. The matchesNode implementation will cut a branch at an occurence of a 'success' node

hmmm, i should definitely look out for suppressed nodes, if there is a better entry point i would be very happy to use it

I quite like the `supressFailureNodes` option and will probably implement it

**possible future**

_cognitive load_

i don't think i understand the output well enough to make any strong claims but filtering by enter/match/fail does help and maybe filtering by "nodes leading to multiple path" and "nodes at the end of a path". (e.g. removing the extra edges in the graph)

_output length_

the output could be reduced, e.g.

```
| | | | 1 + 1
| | | |     ^ # could be removed if the highlighting is background-based on the source
| | | |  # could be removed
```

i don't think printing the source on the same line as the path would improve readability/easy scanning

also the line/column numbers could be hidden (it's already grayed out and shown by the highlighting of the source)

------

as my use case grows more complex i will probably add those, first i'm trying out the node matching approach in my code

meanwhile i'm iterating on what the best output would be for me

**Comment by okaxaki** [comment]
Hi, thank you for a kind replying and considering many things.

**adding options**
> i think the node part is essential as it allows to do any kind of custom filtering (i have an option to grep the node path for instance and i think i will add more)

I agree with you. The node is essential for custom filtering for advanced users. In my last comment, I did not consider such a flexible filtering.

> i would rather have only one interface to get the graph, e.g. only getParseTreeString() and remove getBacktraceString(). and then pass options to getParseTreeString(), e.g. getParseTreeString({ types: ['rule.fail'] }) for instance

I also think the interface should be so. As for compatibility, i think it is good to leave getBacktraceString() as alias for corresponding getParseTreeString() call.

**possible future**
Yes, I think there are many possible improvements for backtrace output like your suggestion. 

I created this tool when I wrote [objc2swift](https://github.com/okaxaki/objc2swift). At that moment, my main use case was to get a redundant backtrace tree. When I needed to filter some nodes, I used the normal tracer's output instead of backtrace. Even I thought that there was a good way to for filtering backtrace tree, I had not implemented filtering feature enough... 

 **prettier**
I will cherry-pick your first 5 commits to the master branch. So I'm sorry to trouble you, but could you make pull-requests again for options and docs? (of course when your convenient time!)

Thank you.

**Comment by okaxaki** [comment]
> i don't think printing the source on the same line as the path would improve readability/easy scanning

I think it is depends on case so the custom node formatter is a solution. Another approach is to save getParseTree() result to json for separate viewer/filter tools.

**Comment by localhostdotdev** [comment]
thanks, rebased and making changes in a new branch. pretty much agree with you on everything

**Pull request closed without merging**
